set(CMAKE_SYSTEM_NAME "Windows")
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} /usr/local/cross-tools/${TOOLCHAIN_PREFIX})

set(SDL2_DIR /usr/local/cross-tools/${TOOLCHAIN_PREFIX}/lib/cmake)

set(CMAKE_FIND_ROOT_PATH_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_INCLUDE ONLY)